Improve pre-commit CI output (#352)
- Enable colors in pre-commit in CI
- Output `git status` in color if pre-commit fails in CI

diff --git a/.github/workflows/ci_lint.yml b/.github/workflows/ci_lint.yml
--- a/.github/workflows/ci_lint.yml
+++ b/.github/workflows/ci_lint.yml
@@ -46,4 +46,8 @@ jobs:
       - name: Run Pre-Commit Hooks
         run: |
           cd ${{ github.workspace }}
-          pre-commit run --verbose --all-files
+          if ! pre-commit run --color=always --verbose --all-files ; then
+            echo "Pre-commit failed. Showing git status:"
+            git -c color.status=always status
+            exit 1
+          fi
